name: Build Release

on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
        - 'package.json'
        - 'package-lock.json'

jobs:
  call-pre-build-release:
    - name: Call Pre Build Release
      if: startsWith( github.head_ref, 'release/') 
      uses: rokucommunity/.github/.github/workflows/pre-build-release.yml@master
      with:
        branch: ${{ github.event.inputs.branch }}
        releaseType: ${{ github.event.inputs.releaseType }}
      secrets: inherit

  call-build-release:
    - name: Call Build Release
      needs: [call-pre-build-release]
      uses: rokucommunity/.github/.github/workflows/build-release.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
      secrets: inherit

  call-post-build-release:
    - name: Call Post Build Release
      needs: [call-build-release]
      uses: rokucommunity/.github/.github/workflows/post-build-release.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
      secrets: inherit