name: Initialize Release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: "The branch to create the release from"
        default: "master"
        required: true
      releaseType:
        type: choice
        description: "Type of release: major, minor, patch, prerelease, or custom"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch
          - prerelease
          - custom
      customVersion:
        type: string
        description: "Specified version to use. May include preids."
        default: ""
        required: true
      installDependencies:
        type: boolean
        description: "Install latest RokuCommunity dependencies"
        required: true
        default: true

jobs:
  run:
    uses: rokucommunity/workflows/.github/workflows/initialize-release.yml@master
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseType: ${{ github.event.inputs.releaseType }}
      customVersion: ${{ github.event.inputs.customVersion }}
      installDependencies: ${{ github.event.inputs.installDependencies }}
    secrets: inherit
