name: Build Release

on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize
    paths:
        - 'package.json'
        - 'package-lock.json'

jobs:
  call-1:
      if: startsWith( github.head_ref, 'release/') 
      uses: rokucommunity/.github/.github/workflows/pre-build-release.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
      secrets: inherit

  call-2:
      needs: [call-1]
      uses: rokucommunity/.github/.github/workflows/build-release.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
      secrets: inherit

  call-3:
      needs: [call-2]
      uses: rokucommunity/.github/.github/workflows/post-build-release.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
      secrets: inherit