name: Publish Release

on:
  pull_request:
    types:
        - closed
    paths:
        - 'package.json'
        - 'package-lock.json'

jobs:
  call-publish-release:
    if: startsWith( github.head_ref, 'release/') && (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    uses: rokucommunity/.github/.github/workflows/publish-release.yml@master
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit

    