name: Create Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The version number for this release"
        required: true
      branch:
        description: "The branch to create the release from"
        required: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "22.9.0"
      - run: npx ts-node src/cli.ts create-release --releaseVersion "${{ github.event.inputs.releaseVersion }}" --branch "${{ github.event.inputs.branch }}"
