name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: "The branch to create the release from"
        default: "master"
        required: true
      releaseType:
        type: choice
        description: "The type of release: major, minor, or patch"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "22.9.0"

      - name: Install dependencies
        run: npm ci

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: npx ts-node src/cli.ts create-release --releaseType "${{ github.event.inputs.releaseType }}" --branch "${{ github.event.inputs.branch }}"
