name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: "The branch to create the release from"
        default: "master"
        required: true
      releaseType:
        type: choice
        description: "The type of release: major, minor, or patch"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "22.9.0"

      - name: Install dependencies
        run: npm ci

      - name: Setup bot
        run: |
            git config user.name "rokucommunity-bot"
            git config user.email "93661887+rokucommunity-bot@users.noreply.github.com"

      - name: get RokuCommunity bot token #so the bot's name shows up on all our actions
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create release
        env:
           GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: npx ts-node src/cli.ts create-release --releaseType "${{ github.event.inputs.releaseType }}" --branch "${{ github.event.inputs.branch }}"
