name: Post Build Release

on:
   workflow_call:
    inputs:
        branch:
            type: string
            description: "The branch to create the release from"
            required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@master

      - name: Checkout .github repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/.github
          path: nested-ci

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "22.9.0"

      - name: CD into nested-ci, run npm ci
        run: |
          cd nested-ci
          npm ci
    
      - name: Run upload
        run: npx ts-node src/cli.ts uploadRelease --branch ${{ github.event.inputs.branch }}