name: Pre Build Release

on:
   workflow_call:
    inputs:
        branch:
            type: string
            description: "The branch to create the release from"
            required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout .github repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/.github
          path: nested-ci

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "22.9.0"

      - name: CD into nested-ci, run npm ci
        run: |
          cd nested-ci
          npm ci

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout .github repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/.github
          path: nested-ci

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "22.9.0"

      - name: CD into nested-ci, run npm ci
        run: |
          cd nested-ci
          npm ci

      - name: Run test
        run: npm run test